coordenadas = [['já[...]já', '\\bjá[\\w,\\W]*já\\b', 0],
               ['não apenas[...]como ainda', '\\bnão apenas[\\w,\\W]*como ainda\\b', 0],
               ['não apenas[...]como também', '\\bnão apenas[\\w,\\W]*como também\\b', 0],
               ['não apenas[...]mas ainda', '\\bnão apenas[\\w,\\W]*mas ainda\\b', 0],
               ['não apenas[...]mas também', '\\bnão apenas[\\w,\\W]*mas também\\b', 0],
               ['não apenas[...]senão ainda', '\\bnão apenas[\\w,\\W]*senão ainda\\b', 0],
               ['não apenas[...]senão também', '\\bnão apenas[\\w,\\W]*senão também\\b', 0],
               ['não só[...]como ainda', '\\bnão só[\\w,\\W]*como ainda\\b', 0],
               ['não só[...]como também', '\\bnão só[\\w,\\W]*como também\\b', 0],
               ['não só[...]mas ainda', '\\bnão só[\\w,\\W]*mas ainda\\b', 0],
               ['não só[...]mas também', '\\bnão só[\\w,\\W]*mas também\\b', 0],
               ['não só[...]senão ainda', '\\bnão só[\\w,\\W]*senão ainda\\b', 0],
               ['não só[...]senão também', '\\bnão só[\\w,\\W]*senão também\\b', 0],
               ['não somente[...]como ainda', '\\bnão somente[\\w,\\W]*como ainda\\b', 0],
               ['não somente[...]como também', '\\bnão somente[\\w,\\W]*como também\\b', 0],
               ['não somente[...]mas ainda', '\\bnão somente[\\w,\\W]*mas ainda\\b', 0],
               ['não somente[...]mas também', '\\bnão somente[\\w,\\W]*mas também\\b', 0],
               ['não somente[...]senão ainda', '\\bnão somente[\\w,\\W]*senão ainda\\b', 0],
               ['não somente[...]senão também', '\\bnão somente[\\w,\\W]*senão também\\b', 0],
               ['ora[...]ora', '\\bora[\\w,\\W]*ora\\b', 0],
               ['ou[...]ou', '\\bou[\\w,\\W]*ou\\b', 0],
               ['quer[...]quer', '\\bquer[\\w,\\W]*quer\\b', 0],
               ['seja[...]seja', '\\bseja[\\w,\\W]*seja\\b', 0],
               ['tanto[...]quanto', '\\btanto[\\w,\\W]*quanto\\b', 0],
               ['ainda assim', '\\bainda assim\\b', 0],
               ['assim', '\\bassim\\b', 0],
               ['assim sendo', '\\bassim sendo\\b', 0],
               ['bem como', '\\bbem como\\b', 0],
               ['contudo', '\\bcontudo\\b', 0],
               ['dessarte', '\\bdessarte\\b', 0],
               ['destarte', '\\bdestarte\\b', 0],
               ['e', '\\be\\b', 0],
               ['em vista disso', '\\bem vista disso\\b', 0],
               ['então', '\\bentão\\b', 0],
               ['entretanto', '\\bentretanto\\b', 0],
               ['logo', '\\blogo\\b', 0],
               ['mas', '\\bmas\\b', 0],
               ['nem', '\\bnem\\b', 0],
               ['no entanto', '\\bno entanto\\b', 0],
               ['ou', '\\bou\\b', 0],
               ['por conseguinte', '\\bpor conseguinte\\b', 0],
               ['por isso', '\\bpor isso\\b', 0],
               ['porém', '\\bporém\\b', 0],
               ['portanto', '\\bportanto\\b', 0],
               ['senão', '\\bsenão\\b', 0],
               ['sendo assim', '\\bsendo assim\\b', 0],
               ['só que', '\\bsó que\\b', 0],
               ['todavia', '\\btodavia\\b', 0]]

subordinadas = [['a tal ponto[...]que', '\\ba tal ponto[\\w,\\W]*que\\b', 0],
                ['de tal maneira[...]que', '\\bde tal maneira[\\w,\\W]*que\\b', 0],
                ['de tal modo[...]que', '\\bde tal modo[\\w,\\W]*que\\b', 0],
                ['maior[...]do que', '\\bmaior[\\w,\\W]*do que\\b', 0],
                ['mais[...]do que', '\\bmais[\\w,\\W]*do que\\b', 0],
                ['melhor[...]do que', '\\bmelhor[\\w,\\W]*do que\\b', 0],
                ['menor[...]do que', '\\bmenor[\\w,\\W]*do que\\b', 0],
                ['menos[...]do que', '\\bmenos[\\w,\\W]*do que\\b', 0],
                ['pior[...]do que', '\\bpior[\\w,\\W]*do que\\b', 0],
                ['tal[...]como', '\\btal[\\w,\\W]*como\\b', 0],
                ['tal[...]que', '\\btal[\\w,\\W]*que\\b', 0],
                ['tamanho[...]que', '\\btamanho[\\w,\\W]*que\\b', 0],
                ['tanto[...]que', '\\btanto[\\w,\\W]*que\\b', 0],
                ['tanto assim[...]que', '\\btanto assim[\\w,\\W]*que\\b', 0],
                ['tão[...]como', '\\btão[\\w,\\W]*como\\b', 0],
                ['tão[...]quanto', '\\btão[\\w,\\W]*quanto\\b', 0],
                ['tão[...]que', '\\btão[\\w,\\W]*que\\b', 0],
                ['a fim de que', '\\ba fim de que\\b', 0],
                ['à medida que', '\\bà medida que\\b', 0],
                ['a menos que', '\\ba menos que\\b', 0],
                ['a não ser que', '\\ba não ser que\\b', 0],
                ['à proporção que', '\\bà proporção que\\b', 0],
                ['agora que', '\\bagora que\\b', 0],
                ['ainda que', '\\bainda que\\b', 0],
                ['antes que', '\\bantes que\\b', 0],
                ['ao mesmo tempo que', '\\bao mesmo tempo que\\b', 0],
                ['ao passo que', '\\bao passo que\\b', 0],
                ['apenas', '\\bapenas\\b', 0],
                ['apesar de que', '\\bapesar de que\\b', 0],
                ['assim como', '\\bassim como\\b', 0],
                ['assim que', '\\bassim que\\b', 0],
                ['até que', '\\baté que\\b', 0],
                ['cada vez que', '\\bcada vez que\\b', 0],
                ['caso', '\\bcaso\\b', 0],
                ['como se', '\\bcomo se\\b', 0],
                ['conforme', '\\bconforme\\b', 0],
                ['conquanto', '\\bconquanto\\b', 0],
                ['consoante', '\\bconsoante\\b', 0],
                ['contanto que', '\\bcontanto que\\b', 0],
                ['dado que', '\\bdado que\\b', 0],
                ['de forma que', '\\bde forma que\\b', 0],
                ['de maneira que', '\\bde maneira que\\b', 0],
                ['de modo que', '\\bde modo que\\b', 0],
                ['de sorte que', '\\bde sorte que\\b', 0],
                ['depois que', '\\bdepois que\\b', 0],
                ['desde que', '\\bdesde que\\b', 0],
                ['em que', '\\bem que\\b', 0],
                ['em que pese', '\\bem que pese\\b', 0],
                ['embora', '\\bembora\\b', 0],
                ['enquanto', '\\benquanto\\b', 0],
                ['exceto se', '\\bexceto se\\b', 0],
                ['já que', '\\bjá que\\b', 0],
                ['logo que', '\\blogo que\\b', 0],
                ['malgrado', '\\bmalgrado\\b', 0],
                ['malgrado', '\\bmalgrado\\b', 0],
                ['mesmo que', '\\bmesmo que\\b', 0],
                ['na medida em que', '\\bna medida em que\\b', 0],
                ['nem que', '\\bnem que\\b', 0],
                ['para que', '\\bpara que\\b', 0],
                ['pois que', '\\bpois que\\b', 0],
                ['por maior que', '\\bpor maior que\\b', 0],
                ['por mais que', '\\bpor mais que\\b', 0],
                ['por melhor que', '\\bpor melhor que\\b', 0],
                ['por menor que', '\\bpor menor que\\b', 0],
                ['por menos que', '\\bpor menos que\\b', 0],
                ['por muito que', '\\bpor muito que\\b', 0],
                ['por pior que', '\\bpor pior que\\b', 0],
                ['posto que', '\\bposto que\\b', 0],
                ['quanto maior', '\\bquanto maior\\b', 0],
                ['quanto mais', '\\bquanto mais\\b', 0],
                ['quanto melhor', '\\bquanto melhor\\b', 0],
                ['quanto menor', '\\bquanto menor\\b', 0],
                ['quanto menos', '\\bquanto menos\\b', 0],
                ['quanto pior', '\\bquanto pior\\b', 0],
                ['salvo se', '\\bsalvo se\\b', 0],
                ['se bem que', '\\bse bem que\\b', 0],
                ['segundo', '\\bsegundo\\b', 0],
                ['sem que', '\\bsem que\\b', 0],
                ['sempre que', '\\bsempre que\\b', 0],
                ['tal e qual', '\\btal e qual\\b', 0],
                ['tal qual', '\\btal qual\\b', 0],
                ['todas as vezes que', '\\btodas as vezes que\\b', 0],
                ['uma vez que', '\\buma vez que\\b', 0],
                ['visto como', '\\bvisto como\\b', 0],
                ['visto que', '\\bvisto que\\b', 0]]

duvidosas = [['não obstante', '\\bnão obstante\\b', 0],
             ['pois', '\\bpois\\b', 0],
             ['porquanto', '\\bporquanto\\b', 0],
             ['porque', '\\bporque\\b', 0],
             ['tanto[...]como', '\\btanto[\\w,\\W]*como\\b', 0]]

perigosas = [['como', '\\bcomo\\b', 0],
             ['qual', '\\bqual\\b', 0],
             ['que', '\\bque\\b', 0],
             ['se', '\\bse\\b', 0]]
